# Level 3 to Level 4 script
# Last edited: 9/25/2017 - Nicholas Clark

#### Description:
# This script takes "Level 3" dose-response data generated by the HMS LINCS Center
# at Harvard Medical School (cell counts along with calculated "GR values" and
# relative cell counts, averaged over technical replicates from different plates) 
# and converts it to "Level 4" data - fitted dose-response curve metrics.

#### Input:
# Breast cancer density project
# Level 3: LDS-1262 or HMS dataset 20257 (will be downloaded by script)
# http://lincsportal.ccs.miami.edu/datasets-beta/#/view/LDS-1262

#### Output files:
# lvl4_R_GRmetrics.tsv - fitted GR curve metrics calculated from R package
# lvl4_R_GRvalues.tsv - GR values (used to fit the curves) calculated from R package
# lvl4_matlab_GRmetrics.tsv - fitted GR curve metrics calculated from MATLAB script (if MATLAB is installed)
# lvl4_matlab_GRvalues.tsv - GR values (used to fit the curves) calculated from MATLAB script (if MATLAB is installed)

#### Check for and install necessary packages if needed
if (!require("devtools")) install.packages("devtools")
if (!require("readr")) install.packages("readr")
if (!require("dplyr")) install.packages("dplyr")
if (!require("GRmetrics")) {
  source("https://bioconductor.org/biocLite.R")
  biocLite("GRmetrics")
}
if (!require("LINCSDataPortal")) devtools::install_github("schurerlab/LINCSDataPortal")
if (!require("matlabr")) devtools::install_github("muschellij2/matlabr")

library(readr)
library(dplyr)
library(LINCSDataPortal)
library(matlabr)
library(GRmetrics)

# Download Level 3 dataset
download_dataset("LDS-1262")
untar("LDS-1262.tar.gz", exdir = ".")
system("rm *tar.gz")


# Read dataset into R
lvl3 = read_tsv("LDS-1262/20257.txt")

lvl3_rename = lvl3 %>% dplyr::rename(concentration = `Small Mol Concentration`, cell_count = `Mean Total Cell Count After Treatment`, cell_count__time0 = `Mean Total Cell Count Before Treatment`, cell_count__ctrl = `Mean Total Control Cell Count`)

lvl3_MATLAB_input = lvl3_rename[,c("Cell Name","Small Molecule Name", "Replicate", "Seeding Density",
          "concentration", "cell_count__time0", "cell_count__ctrl", "cell_count")]

# Write file for MATLAB script input
write_tsv(lvl3_MATLAB_input, path = "lvl3_MATLAB_input.tsv")

# Download MATLAB scripts
url1 = "https://raw.githubusercontent.com/datarail/gr_metrics/master/SRC/MATLAB/GRmetrics.m"
download.file(url1, "GRmetrics.m")
url2 = "https://raw.githubusercontent.com/datarail/gr_metrics/master/SRC/MATLAB/evaluate_GRmetrics.m"
download.file(url2, "evaluate_GRmetrics.m")
url3 = "https://raw.githubusercontent.com/datarail/gr_metrics/master/SRC/MATLAB/evaluate_GRvalue.m"
download.file(url3, "evaluate_GRvalue.m")

# Calculate GR metrics by running MATLAB script through R (if MATLAB is available)
if( have_matlab() ) {
  run_matlab_code("GRmetrics('lvl4_matlab', 'lvl3_MATLAB_input.tsv'); exit;")
}

# Or calculate GR metrics in R
GRmet = GRfit(lvl3_rename, c("Cell Name", "Small Molecule Name", "Replicate", "Seeding Density"))
GRmet_lvl4 = GRgetMetrics(GRmet)
GRval_lvl4 = GRgetValues(GRmet)
write_tsv(GRmet_lvl4, "lvl4_R_GRmetrics.tsv")
write_tsv(GRval_lvl4, "lvl4_R_GRvalues.tsv")
